### ISSUE TITLE
rclone.conf owner is not correct for new users

### ISSUE THREAD

**Issue by annefou** [destination-earth/DestinE_ESA_GFTS#109]
I understand that the owner of the rclone configuration file we created is incorrect. As a result, end-users cannot modify the config file, which is an issue because we need to update it to add new entries.

However, I’m not sure how to change the owner in `gfts-track-reconstruction/jupyterhub/gfts-hub/values.yaml`.

Am I correct @tinaok 

Any idea @minrk ?

**Comment by minrk** [comment]
We can change the ownership with

```
chown -R 1000:1000 /homedir/.config/rclone
```

after creating the file. But if you are modifying the file after creating it, you'll lose those changes on each launch, so we should perhaps change how we load the default config so it's not in a place users want to edit. #110 should move  the config to environment variables, and fix the permissions on launch.
